

## team
#team_list:
#  pattern:  /team
#  defaults: { _controller: AapBluebirdsBundle:Team:list }
#
#team_create:
#  pattern: /team/create
#  defaults: { _controller: AapBluebirdsBundle:Team:create }
#
#team_detail:
#  pattern:  /team/{id}
#  defaults: { _controller: AapBluebirdsBundle:Team:detail }
#
#team_edit:
#  pattern: /team/{id}/edit
#  defaults: { _controller: AapBluebirdsBundle:Team:edit }
#
#team_delete:
#  pattern: /team/{id}/delete
#  defaults: { _controller: AapBluebirdsBundle:Team:delete }
#  # make sure it is a post
#
## member
#member_list:
#  pattern:  /member
#  defaults: { _controller: AapBluebirdsBundle:Member:list }
#
#member_create:
#  pattern: /member/create
#  defaults: { _controller: AapBluebirdsBundle:Member:create }
#
#member_detail:
#  pattern:  /member/{id}
#  defaults: { _controller: AapBluebirdsBundle:Member:detail }
#
#member_edit:
#  pattern: /member/{id}/edit
#  defaults: { _controller: AapBluebirdsBundle:Member:edit }
#
#member_delete:
#  pattern: /member/{id}/delete
#  defaults: { _controller: AapBluebirdsBundle:Member:delete }
#  # make sure it is a post
#
## player
#player_create:
#  pattern: /team/{team_id}/player/create
#  defaults: { _controller: AapBluebirdsBundle:Player:create }
#
#player_edit:
#  pattern: /team/{team_id}/player/{id}/edit
#  defaults: { _controller: AapBluebirdsBundle:Player:edit }
#
#player_delete:
#  pattern: /team/{team_id}/player/{id}/delete
#  defaults: { _controller: AapBluebirdsBundle:Player:delete }

bootstrap_demo:
  pattern: /bootstrap
  defaults: { _controller: AapBluebirdsBundle:Bootstrap:index }