team_list:
  pattern:  /teams
  defaults: { _controller: AapBluebirdsBundle:Team:list }

team:
  pattern:  /team/{slug}
  defaults: { _controller: AapBluebirdsBundle:Team:team }

team_create:
  pattern: /teams/create
  defaults: { _controller: AapBluebirdsBundle:Team:create }

bootstrap_demo:
  pattern: /bootstrap
  defaults: { _controller: AapBluebirdsBundle:Bootstrap:index }