# overview
overview:
    pattern: /
    defaults: { _controller: AapBluebirdsBundle:Overview:index }

# positions
position_list:
    pattern: /admin/positions
    defaults: { _controller: AapBluebirdsBundle:Position:list }
position_create:
    pattern: /admin/positions/create
    defaults: { _controller: AapBluebirdsBundle:Position:create }
position_edit:
    pattern: /admin/positions/edit/{id}
    defaults: { _controller: AapBluebirdsBundle:Position:edit }
position_detail:
    pattern: /admin/positions/detail/{id}
    defaults: { _controller: AapBluebirdsBundle:Position:detail }
position_delete:
    pattern: /admin/positions/delete/{id}
    defaults: { _controller: AapBluebirdsBundle:Position:delete }

# clubs
club_list:
    pattern: /admin/clubs
    defaults: { _controller: AapBluebirdsBundle:Club:list }
club_create:
    pattern: /admin/clubs/create
    defaults: { _controller: AapBluebirdsBundle:Club:create }
club_edit:
    pattern: /admin/clubs/edit/{id}
    defaults: { _controller: AapBluebirdsBundle:Club:edit }
club_detail:
    pattern: /admin/clubs/detail/{id}
    defaults: { _controller: AapBluebirdsBundle:Club:detail }
club_delete:
    pattern: /admin/clubs/delete/{id}
    defaults: { _controller: AapBluebirdsBundle:Club:delete }

# teams
team_list:
    pattern: /admin/teams
    defaults: { _controller: AapBluebirdsBundle:Team:list }
team_create:
    pattern: /admin/teams/create
    defaults: { _controller: AapBluebirdsBundle:Team:create }
team_edit:
    pattern: /admin/teams/edit/{id}
    defaults: { _controller: AapBluebirdsBundle:Team:edit }
team_detail:
    pattern: /admin/teams/detail/{id}
    defaults: { _controller: AapBluebirdsBundle:Team:detail }
team_delete:
    pattern: /admin/teams/delete/{id}
    defaults: { _controller: AapBluebirdsBundle:Team:delete }

# members
member_list:
    pattern: /admin/members
    defaults: { _controller: AapBluebirdsBundle:Member:list }
member_create:
    pattern: /admin/members/create
    defaults: { _controller: AapBluebirdsBundle:Member:create }
member_edit:
    pattern: /admin/members/edit/{id}
    defaults: { _controller: AapBluebirdsBundle:Member:edit }
member_detail:
    pattern: /admin/members/detail/{id}
    defaults: { _controller: AapBluebirdsBundle:Member:detail }
member_delete:
    pattern: /admin/members/delete/{id}
    defaults: { _controller: AapBluebirdsBundle:Member:delete }

# team_members
team_member_list:
    pattern: /admin/team_members/{team_id}
    defaults: { _controller: AapBluebirdsBundle:TeamMember:list }
team_member_create:
    pattern: /admin/team_members/{team_id}/create
    defaults: { _controller: AapBluebirdsBundle:TeamMember:create }
team_member_edit:
    pattern: /admin/team_members/{team_id}/edit/{id}
    defaults: { _controller: AapBluebirdsBundle:TeamMember:edit }
team_member_detail:
    pattern: /admin/team_members/{team_id}/detail/{id}
    defaults: { _controller: AapBluebirdsBundle:TeamMember:detail }
team_member_delete:
    pattern: /admin/team_members/{team_id}/delete/{id}
    defaults: { _controller: AapBluebirdsBundle:TeamMember:delete }


## player
#player_create:
#  pattern: /team/{team_id}/player/create
#  defaults: { _controller: AapBluebirdsBundle:Player:create }
#
#player_edit:
#  pattern: /team/{team_id}/player/{id}/edit
#  defaults: { _controller: AapBluebirdsBundle:Player:edit }
#
#player_delete:
#  pattern: /team/{team_id}/player/{id}/delete
#  defaults: { _controller: AapBluebirdsBundle:Player:delete }

bootstrap_demo:
  pattern: /bootstrap
  defaults: { _controller: AapBluebirdsBundle:Bootstrap:index }